### ISSUE TITLE
Is Nut specific to "legacy" lxc or does it work with lxd?

### ISSUE THREAD

**Issue by bmullan** [PagerDuty/Nut#25]
I moderate 2 subreddits.  

One for the "legacy" LXC (https://www.reddit.com/r/LXC/) 
and 
one for the newer LXD (https://www.reddit.com/r/LXD/).

Someone posted a reference to the github NUT page but looking at the page I see reference to lxc-create which is the older style LXC syntax.

Thought I'd ask if NUT also works with LXD?

If not I will move that reference to the LXC subreddit so as not to confuse anyone reading about it.

thanks

**Comment by ranjib** [comment]
@bmullan nut uses  liblxc, it is not LXD aware. You can omit nut's reference from LXD related posts. Its a tool for building LXC container with dockerfile like specification file. I run it on ubuntu 16.04 against liblxc 2.0, and it works fine. Let me know if theres anything specific to lxc 2.0 that is not working.
